    name: GitHub Classroom Workflow

# Allow students to launch workflow manually.
    on:
      workflow_dispatch:
      push:
        tags:
          - checkMe*

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
